# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *

libs = ['NuMemory_static']

AlkyLib('advapi32', ['AdvApi32.c', 'Registry.c'], LIBS=libs)
# AlkyTest('Test')