# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *

AlkyLib('NuFile', ['File.c', 'Glob.c'], LIBS=['NuContext', 'NuMemory_static'])

# AlkyTest('Test')