# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *
libs = []
frameworks = []
AlkyLib('wsock32', ['WSock32.c'], FRAMEWORKS=frameworks, LIBS=libs)
# AlkyTest('Test')
