foo = """
    NOP          = 0,
    MOV          ,
    ADD          ,
    SUB          ,
    MAD          ,
    MUL          ,
    RCP          ,
    RSQ          ,
    DP3          ,
    DP4          ,
    MIN          ,
    MAX          ,
    SLT          ,
    SGE          ,
    EXP          ,
    LOG          ,
    LIT          ,
    DST          ,
    LRP          ,
    FRC          ,
    M4x4         ,
    M4x3         ,
    M3x4         ,
    M3x3         ,
    M3x2         ,
    CALL         ,
    CALLNZ       ,
    LOOP         ,
    RET          ,
    ENDLOOP      ,
    LABEL        ,
    DCL          ,
    POW          ,
    CRS          ,
    SGN          ,
    ABS          ,
    NRM          ,
    SINCOS       ,
    REP          ,
    ENDREP       ,
    IF           ,
    IFC          ,
    ELSE         ,
    ENDIF        ,
    BREAK        ,
    BREAKC       ,
    MOVA         ,
    DEFB         ,
    DEFI         ,

    TEXCOORD     = 64,
    TEXKILL      ,
    TEX          ,
    TEXBEM       ,
    TEXBEML      ,
    TEXREG2AR    ,
    TEXREG2GB    ,
    TEXM3x2PAD   ,
    TEXM3x2TEX   ,
    TEXM3x3PAD   ,
    TEXM3x3TEX   ,
    RESERVED0    ,
    TEXM3x3SPEC  ,
    TEXM3x3VSPEC ,
    EXPP         ,
    LOGP         ,
    CND          ,
    DEF          ,
    TEXREG2RGB   ,
    TEXDP3TEX    ,
    TEXM3x2DEPTH ,
    TEXDP3       ,
    TEXM3x3      ,
    TEXDEPTH     ,
    CMP          ,
    BEM          ,
    DP2ADD       ,
    DSX          ,
    DSY          ,
    TEXLDD       ,
    SETP         ,
    TEXLDL       ,
    BREAKP       ,

    PHASE        = 0xFFFD,
    COMMENT      = 0xFFFE,
    END          = 0xFFFF,
"""

i = 0

for line in foo.split('\n'):
	line = line.strip().replace('\t', ' ')
	line = line.strip().split(' ', 1)
	
	if len(line) == 0 or len(line) == 1:
		continue
	
	print 'string_map[%s] = %r' % (line[0], line[0])
	i += 1
