# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *

SConscript(
	[
		'D3D/SConscript',
		'D3DX/SConscript',
		'DInput/SConscript',
		'DSound/SConscript'
	]
)