# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *

libs = ['NuContext', 'NuMemory_static', 'NuCore_static']

AlkyLib('WBEM', ['WBEM.c', 'Context.c'], LIBS=libs)
# AlkyTest('Test')