# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *

AlkyLib('NuMemory', ['Memory.c', 'Heap.c', 'TLS.c'], LIBS=['NuContext'])

# AlkyTest('Test')