# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import env

env.Program('TestFile', ['TestFile.c'], LIBS=['NuFile_static', 'SDLmain'], LIBPATH='../')