# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *

AlkyLib('NuCore', ['Core.c', 'Import.c'], LIBS=['NuContext', 'NuMemory_static'])
# AlkyTest('Test')