# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *

libs = ['NuContext', 'NuMemory_static']
if 'darwin' in sys.platform:
    frameworks = ['OpenGL', 'SDL']
else:
    frameworks = ['GL', 'SDL']
AlkyLib('NuGUI', ['Class.c', 'Event.c', 'GUI.c', 'Mouse.c', 'Window.c', 'Time.c'], FRAMEWORKS=frameworks, LIBS=libs)

# AlkyTest('Test')
