# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *

libs = ['NuContext', 'NuMemory_static', 'NuCore_static']
if 'darwin' in sys.platform:
    frameworks = ['OpenGL', 'SDL']
else:
    frameworks = ['GL', 'SDL']
AlkyLib('opengl32', ['OpenGL32.c'], FRAMEWORKS=frameworks, LIBS=libs)
# AlkyTest('Test')
