# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *

libs = ['NuContext', 'NuMemory_static', 'NuCore_static', 'COM_static']

AlkyLib('dsound', ['DSound.c'], LIBS=libs)