# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *

libs = ['NuContext', 'NuMemory_static']
AlkyLib('NuEvent', ['Event.c', 'Timer.c'], LIBS=libs)

# AlkyTest('Test')
