# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *

libs = ['NuContext', 'NuMemory_static', 'NuCore_static']

AlkyLib('ole32', ['OLE32.c'], LIBS=libs)
# AlkyTest('Test')