# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *
libs = ['NuContext', 'NuMemory_static']
frameworks = []
AlkyLib('oleaut32', ['OLEAUT32.c'], FRAMEWORKS=frameworks, LIBS=libs)
# AlkyTest('Test')
