# Copyright 2006 Falling Leaf Systems, LLC.
# Refer to LICENSE in the root directory.

from scons_util import *
libs = ['NuContext', 'NuMemory_static', 'NuGUI_static', 'NuThread_static']

if not 'darwin' in sys.platform:
	libs.append('pthread')

frameworks = ['SDL']
AlkyLib('wincore', ['Core.c'], FRAMEWORKS=frameworks, LIBS=libs)
# AlkyTest('Test')
